name: HaxRDP

on: [push, workflow dispatch]

jobs:

build:

runs-on: windows-latest

steps:

- name: DOWNLOADING

run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA71aHb/ngrok-stable-windows

amd64.zip -OutFile ngrok.zip

- name: EXTRACT

run: Expand-Archive ngrok.zip

- name: AUTENTIFIKASI

run: .\ngrok\ngrok.exe authtoken 2F7HpwtwnNXlQ8C2keKkcykqKjp_72LTuNLagQRyzVb1GAXUm

- name: ENABLE TS

run: Set-ItemProperty -Path 'HKLM\System\CurrentControlSet\Control\Terminal Server'-name "DenyTSConnections" -Value 0

- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

- run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString –

AsPlainText "Password!" -Force)

- name: DONE!

run: .\ngrok\ngrok.exe top 3389
